### ISSUE TITLE
Additional Closing Brace in TrustFrameworkExtensionsSeamlessMigration.xml

### ISSUE THREAD

**Issue by nicholasrsky** [azure-ad-b2c/user-migration#12]
Thanks for all your work on this project--it has been extremely useful to me in implementing a custom B2C sign in for users migrating from another system. Whilst working with the project, I noticed a small typo in the TrustFrameworkExtensionsSeamlessMigration.xml file--there is an additional closing brace on line 141:

`<PersistedClaim ClaimTypeReferenceId="passwordPolicies" DefaultValue="DisablePasswordExpiration, DisableStrongPassword" AlwaysUseDefaultValue="true"/>/>`

**Comment by JasSuri** [comment]
Fixed
