### ISSUE TITLE
Cannot  Register an requiresMigration Attribute  in seamless-account-migration

### ISSUE THREAD

**Issue by saq1bahmed** [azure-ad-b2c/user-migration#13]
Getting the following error when running part 2  of the script. ...

Invoke-WebRequest : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"Updates to converged applications are not 
allowed in this version."},"requestId":"d5c452eb-8555-4cdb-827a-e30d1b2e7326","date":"2020-06-17T05:19:11"}}
At line:34 char:11
+ $result = Invoke-WebRequest -Headers $authHeader -Uri $url -Method Po ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At line:37 char:20
+ ($result.Content | Convertfrom-Json).name
+                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Invoke-WebRequest : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"The following extension properties are not 
available: extension_29f3a41ad6bc4e77bb65d4d4ff5a3947_requiresMigration."},"requestId":"4d66bd5a-fff5-449f-9136-1534b7764f5c","date":"2020-06-1
7T05:19:12"}}
At line:87 char:1
+ Invoke-WebRequest -Headers $authHeader -Uri $url -Method Post -Body $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

The Script 

#Part 2 - Register the extension attribute named "requiresMigration" into Azure AD B2C
#ObjectID of the B2CUserMigration App Registration
$AppObjectID = ""

#Set the endpoint to register extension attributes
$url = "https://graph.windows.net/$tenant/applications/$AppObjectID/extensionProperties?api-version=1.6"

#Define the extension attribute
$body = @"
{ 
 "name": "requiresMigration", 
 "dataType": "Boolean", 
 "targetObjects": ["User"]
}
"@

#Generate the authentication header and make the request
$authHeader = @{"Authorization"= $oauth.access_token;"Content-Type"="application/json";"ContentLength"=$body.length }
$result = Invoke-WebRequest -Headers $authHeader -Uri $url -Method Post -Body $body

#Print the full attribute Name
($result.Content | Convertfrom-Json).name

**Comment by JasSuri** [comment]
Converged apps refer to Native Application registrations, and Multi tenant application registrations. When creating an application registration which will be used to extend the Schema, either use the [built in app](b2c-extensions-app. Do not modify. Used by AADB2C for storing user data.) (recommended), or create an App Reg of type "Accounts in this organization only".
