### ISSUE TITLE
ROPC : Does the user-migration with Sign-In & Rest-API to validate user on Legacy IDP work for ROPC ?

### ISSUE THREAD

**Issue by sudhakarbetha** [azure-ad-b2c/user-migration#14]
ROPC : Does the user-migration with Sign-In & Rest-API to validate user on Legacy IDP work for ROPC ?

We are using a mobile  device and have users to  migrate  from an Database as part of Migration,
I followed 
1) ROPC Custom Policy  https://docs.microsoft.com/en-us/azure/active-directory-b2c/ropc-custom?tabs=app-reg-ga
2) Defined custom attributes https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-custom-attributes
3) Setup a Rest-API on Legacy IDP to return migrationStatus 
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-rest-api-intro

However, I think the ROPC with REST-API is not supported ? because the 
ROPC has Protocol Name="OpenIdConnect" />
vs 
SelfAsserted-LocalAccountSignin-Email has <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />

and  ran into problem of
Invalid technical profile with id "ResourceOwnerPasswordCredentials-OAUTH2" only the protocol handler ""Web.TPEngine.Providers.SelfAssertedAttributeProvider"" can have a ValidationTechnicalProfile

I stumbled upon these and noticed, the migration does not apply for ROPC (mobile devices) ? Is that true ?
https://docs.microsoft.com/en-us/azure/active-directory-b2c/self-asserted-technical-profile
https://docs.microsoft.com/en-us/azure/active-directory-b2c/openid-connect-technical-profile

Can someone tell me how do we do migration during SignIn with Rest-API interaction for ROPC grant_type ?

**Comment by JasSuri** [comment]
This should work now, in the past what you observed is accurate.

**Comment by malta895** [comment]
Hi @JasSuri,
could you provide an XML example of a user journey and technical profiles of the steps you mentioned? In particular I can't figure out how to implement the first and the second step. 

What do you mean by "Read the directory by email"?

How can I insert the password in the REST API body?
