### ISSUE TITLE
Missing Base file

### ISSUE THREAD

**Issue by eb-safenet** [azure-ad-b2c/user-migration#16]
In in documentation instructions, the first file to upload is SeamlessMigration_TrustFrameworkBase.xml 
https://github.com/azure-ad-b2c/user-migration/tree/master/seamless-account-migration#upload-the-policy-to-your-tenant

But that file is not included in the project
https://github.com/azure-ad-b2c/user-migration/tree/master/seamless-account-migration/policy

I have been trying to use the base file from the custom policy starter pack, but am getting several errors when uploading the seamless migration files. 

Thanks,
-Eric

**Comment by jackalvrus** [comment]
I also need this file.

**Comment by JasSuri** [comment]
It should chain to the base file from starter pack, I will check this.

**Comment by JasSuri** [comment]
Tested with https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/SocialAndLocalAccountsWithMfa

Seamlessmigration Extension file chains without errors to the above.
