### ISSUE TITLE
seamless migration xml configuration problem

### ISSUE THREAD

**Issue by cd425** [azure-ad-b2c/user-migration#28]
When I use the [tool](https://aka.ms/iefsetup), it can't read the property requiresMigration, so no request to our identity API.
When I set the default value to true, it called our API but does not update the requiresMigration (but password got changed und login with new password works).
`<OutputClaim ClaimTypeReferenceId="requiresMigration" PartnerClaimType="extension_requiresMigration" DefaultValue="true" />`
At first I have tried the[ sampleconfigs](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/LocalAccounts), the flag got flipped, but I can't sign in.
How can I fix this? Thanks

**Comment by dle12** [comment]
After granting the permissions (which the tool fail to do), now it can read the flag, but the flag still does not flip.

**Comment by cd425** [comment]
It seems I config the extension attribute wrong. It's working now
