### ISSUE TITLE
Seamless user migration Error

### ISSUE THREAD

**Issue by softcloudservices** [azure-ad-b2c/user-migration#31]
Hi Team, @JasSuri @felickz @altenstedt @yoelhor 

I am getting following error when trying to  call a secure rest API  to validate password:

![image](https://user-images.githubusercontent.com/63921850/163203574-2c5cb874-680f-42e3-a33f-10b4b84ba5d6.png)

i also validated the  client id and secrete using postman i am able to generate a access token .

Here is the link to the Framework file https://github.com/softcloudservices/AADHTTP/blob/master/TrustFrameworkExtensions_PasswordValidation%20-%20Copy.xml

Please let me know if you need anything from myside.
Here are the details of the policy correlationID:

![image](https://user-images.githubusercontent.com/63921850/163204397-6a3e2f9e-757e-4f62-9d41-156d06d32ee4.png)

Thanks,
Shiva

**Comment by JasSuri** [comment]
Please provide correlationIds in text form. Difficult to type out a GUID.

Can you change this as follows:
```xml
            <InputClaim ClaimTypeReferenceId="grant_type_Api_Token" PartnerClaimType="grant_type" DefaultValue="client_credentials" AlwaysUseDefaultValue="true"/>
            <InputClaim ClaimTypeReferenceId="scope_Api_Token"  PartnerClaimType="scope" DefaultValue="api://xxx/xxx/.default" AlwaysUseDefaultValue="true"  />
```

And define a string claim for `grant_type_Api_Token` and `scope_Api_Token`.

You need to use App Insights to [debug your policies](https://docs.microsoft.com/en-us/azure/active-directory-b2c/troubleshoot-with-application-insights?pivots=b2c-custom-policy) to understand what exactly is causing the error. You will also be able to see your claim values in the claimbag prior to this API call to understand if things are correct.

This Git issues is for bugs in the policy, and not config advice, hence i will close this. You can try StackOverflow or open a Microsoft Support ticket instead.
