### ISSUE TITLE
Just-in-time migration links broken?

### ISSUE THREAD

**Issue by nezoic** [azure-ad-b2c/user-migration#9]
https://github.com/Azure-Samples/active-directory-b2c-advanced-policies/blob/master/Migration-JIT-sample/Just%20in%20time%20migration%20in%20pictures%2002242017.pptx

is no longer a valid repository. Is there a new recommendation for migrating users?

**Comment by yoelhor** [comment]
This is the new repo for JIT migration https://github.com/azure-ad-b2c/user-migration
